### ISSUE TITLE
Players can move to spec, stuck on spec or coach

### ISSUE THREAD

**Issue by royysz** [splewis/get5#104]
If making a feature request, you should delete all the pre-filled text here.
If reporting a bug, fill in the following sections:

### Expected behavior

sometimes when 9 players are on the server and the 10th player tries to return he cant go on to his team, only when i do "bot_kick" he can(no bots in the server).

another problem is the coach, is there an option to disable it? players can just randomly switch to coach with no command to go back to their side.

### Steps to reproduce
- Plugin version:
- Sourcemod version:

**Comment by Technoblazed** [comment]
1) If you have GoTV enabled, the GoTV bot counts as a bot client. So you'd need an 11 slot server.

2) Check your /csgo/cfg/get5 configs, and change every instance of `sv_coaching_enabled` to `0`.

**Comment by splewis** [comment]
I'm a little confused. 

What does: "cant go on his team" mean? He gets kicked from the server? Put in the coach slot? Pressing a team in the teamjoin menu does nothing?

"Players can just randomly switch to coach with no command to go back" - joining a full team or typing !coach doesn't seem that random to me, is it happening otherwise?

Can you post what plugin version you were using as well?

**Comment by royysz** [comment]
"plugin_version": "0.4.1-dev+239"
you can reproduce this if you spam the enter key when there are 9/10 players on the server, it will move you to the spec.
