### ISSUE TITLE
New API HTTP POST on series start event

### ISSUE THREAD

**Issue by gabrielfgularte** [splewis/get5#150]
I'm trying to add a HTTP POST on the series start event (I think it is the `Get5_OnSeriesInit` function). But it fails beacuse SteamWorks says that I'm `Not using a web interface.`

I noticed that are two lines on the live event (`Get5_OnGoingLive` function) that are bounded in some way to the url and api_key (`Get5_AddLiveCvar("get5_web_api_key", g_APIKey)` and `Get5_AddLiveCvar("get5_web_api_url", g_APIURL)`), but I don't understand how. These lines are declared after the live event request.

All other http requests are working fine. Maybe at the time that the series start event is triggered, the plugin is not read yet to make http requests?

**Comment by splewis** [comment]
I'm not sure I understand. This isn't a bug report or feature request, but you trying to change the get5_apistats plugin? I can't really provide support for arbitrary modifications. 

>  But it fails beacuse SteamWorks says that I'm Not using a web interface.

I don't know what that means. SteamWorks provides a bunch of functions get5_apistats uses, it doesn't "say anything" itself.

From what I'm guessing, you're creating an http request before the api key/url are being set, so the requests are failing.

**Comment by gabrielfgularte** [comment]
Sorry. My English is rusty. And I'm very new on the csgo/mods scenario. So it's hard to me explain exactly what I want to say. But you got the general idea. :)

Basically, I'm trying to change the get5_apistats plugin, yes. And I think this can be a nice feature. What I want, is to send a Http post on the series_start event. There's already one for the series end (/match/%d/finish) and I think that would be good to have one for the start (/match/%d/start). I've tried to paste the code above in the `Get5_OnSeriesInit` (https://github.com/splewis/get5/blob/master/scripting/get5_apistats.sp#L149) function:
```
Handle req = CreateRequest(k_EHTTPMethodPOST, "match/%d/start", g_MatchID);
if (req != INVALID_HANDLE) {
  SteamWorks_SendHTTPRequest(req);
}
```

But it doesn't work. There's a commented code here: https://github.com/splewis/get5/blob/master/scripting/get5_apistats.sp#L118 that after some debugging I've figured that is why the HTTP POST is not working.

**Comment by splewis** [comment]
Note that the get5_apistats plugin is *only* designed to work against the official [web interface](https://github.com/splewis/get5-web), not to use a general purpose API (which is why there is no clear documentation on said http API, it's essential an implementation detail of the get5_apistats->web interface communication).

This is relevant because it means unless the web interface has an API endpoint for match start, there's no reason for get5_apistats to do something there.

For a user with their own web API endpoints, they should create a separate plugin. Of course, you could base it off get5_apistats. 

As for your specific question: the plugin keeps an API key in get5_web_api_key. It adds that to every request as ``key``. Maybe you want that, maybe you don't. https://github.com/splewis/get5-web does use it. If you don't set that cvar, which the panel does over rcon, you will run into this problem.

**Comment by gabrielfgularte** [comment]
Alright, I'll figure out other ways to do that so.

Thank you and congratulations for your work here! :)
