### ISSUE TITLE
Why there's no `get5_knife_cfg` cVar?

### ISSUE THREAD

**Issue by gabrielfgularte** [splewis/get5#157]
Hi there!

There is a `get5_warmup_cfg` and a `get5_live_cfg`, but there's no `get5_knife_cfg`. Why is that? 

I've noticed that the `knife` config file is a constant (`KNIFE_CONFIG`) and the function handling it is `ExecuteAndSaveCvars`, but the function used to load the `live` and `warmup` configs is so much simple and clean (`ExecCfg`).

Could you help me to understand it? Is it possible to add the `get5_knife_cfg` as a cVar?

Thank you!

**Comment by splewis** [comment]
Because I didn't want to add extra cvars that I didn't see a clear use for.

Using the save & restore settings for knife configs helps make it so the live config doesn't have to undo settings - many configs don't set the default primary weapons, for example, so having the plugin undo the knife config's setting of that cvar helps.

**Comment by splewis** [comment]
I'm closing since I don't plan on adding that cvar.

If you feel the cvar is important, you can reopen and explain why.
