### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by oalaro** [splewis/get5#16]
I've used Warmod plugin to organize lans before. Since it's not updated anymore been looking for a replacement that is somewhat good. Since your other plugins are very good, hoping this will be as good. For running a small tournament, currently this plugin would suit perfectly. But running a 32+ team LAN wouldn't be so easy during the group stage. So here are some suggestions.

- Add some way to add team captains to some local file. So if one captain joins a team that team will automatically have team name and country set like warmod had its captains file. http://pastebin.com/raw/whpRebw2

- Captains can 1v1 knife on who starts the veto process. Warmod had 5v5 knife for that, but id proved to be somewhat time consuming. 

- Captains can choose if they want veto BO1,BO3 or BO5 with a chat command. Warmod had default veto set for BO1. If both captains would write !vetobo3 it would choose that veto process instead.

**Comment by splewis** [comment]
Having a captains file would conflict with the design principle of defining the match inside a single config file. I know it could be tedious to write on its own, ideally there will be some web-frontend to make managing those easier as same point (saved team data, saved match data, etc. for easy reuse/management)

Not a fan of using knifing for that, don't think it's worth the effort to support that, especially since it's never done in normal competition.

Letting players type commands like that also goes against the use of the match config file. There should be as few client commands as possible, imo.
