### ISSUE TITLE
Readyup timer isn't synced when one team choose to ready and then becomes unready again.

### ISSUE THREAD

**Issue by grenadecx** [splewis/get5#160]
If making a feature request, you should delete all the pre-filled text here.
If reporting a bug, fill in the following sections:

### Expected behavior
When enabling max 5 minutes timer for the readycheck (or else forfeit) and ct becomes ready, waits 30 seconds and becomes unready. The time is suppose to be the same for ct and t. I also expect the time to be announced at the same time for the teams.

### Actual behavior
When enabling max 5 minutes timer for the readycheck (or else forfeit) and ct becomes ready, waits 30 seconds and becomes unready. The time for forfeit is now different for t and ct, where ct have a longer timer which is now incorrect. Announcment of the time left is also no longer announced at the same time for the teams.

### Steps to reproduce
Set get5_time_to_start to 300.
Start game, and as ct, ready up, wait 30 seconds and unready. The time for both teams will no longer match and they will not be announced at the same time.

- Plugin version: 0.5.3-dev
- Sourcemod version: 1.8.0.6001

**Comment by splewis** [comment]
Thanks for the clear bug report!

I don't have time to look into it now, but I'll try to get around to it in around a week.

**Comment by miped** [comment]
I think this is a misunderstanding of how the feature is meant to be used. It is meant to be per team. This means that it's not a "global" 5 minutes to start for instance.

The idea is that each team has a certain amount of time to ready up. Once they've used up that time, they will forfeit the match. It is done this way so that teams have an incentive to ready up. If you make the timer global, then this can happen:

* Team 1 joins and readies up immediately. They're here to play, and they just wanna get started.
* Team 2 joins and dicks around. Doesn't ready up.
* Global timer reaches zero, because team 2 is still dicking around. 
* Match is stopped without any winner, or even worse, the wrong team is forfeited.

It would be fine to add a global ready time as well, but that's a different feature from the one implemented (which works as expected btw).

**Comment by splewis** [comment]
@miped 

In your example, the match should just be a forfeit for team2 since they're not ready at (match_init_time + k seconds). That seems reasonable to me, or am I missing something?

(I do agree this could be seen as working correctly and being a separate feature request, and I could imagine a cvar for picking between whether ready up time is global or per-team, but this global method seems correct to me)

**Comment by miped** [comment]
Well you could argue that, but leaving it global also gives a team the option of "running down the clock".

Consider this:
* Global timer is 5 minutes
* Team 2 joins and dicks around.
* Team 1 joins and readies up. They stay readied up for 4:30 minutes.
* Global timer is now at 30 seconds.
* Something happens that makes team 1 unready (maybe one of the players is going to talk to an admin to get team2 to stop dicking around?)
* Meanwhile, team 2 readies up

When the timer reaches 0:00, team2 is ready but team1 is not. Yet, team1 has been ready for 4 minutes and 30 seconds out of the last 5 minutes. Team2 has been ready for 30 seconds. Is it fair that team1 gets forfeited?

With the existing implementation, team2 will have 30 seconds left to ready up, whereas team1 will have 4 minutes and 30 seconds.

If the issue is that the messages are "out of sync", then let's fix that (even though i don't see that as an issue tbh).

If the issue is that setting the timer to 5 minutes means that it could effectively take 10 minutes for the game to start (team1 dicks around for 4:59, then team2 does the same), this will very rarely happen, as it requires a team to ready up, and then unready afterwards. Also, once you know this, it's easy to adjust (e.g. setting the timer to 2 minutes and 30 seconds to effectively cap the time at 5 minutes). This should be solved with documentation instead.

**Comment by splewis** [comment]
Thanks. I thought about that line of reasoning, but figured "team1 just shouldn't ready up!"
Your example shows that might be a bad idea :)

The problem with the current system is that it makes it hard to enforce starting a match on time, since the wait time could be used up entirely by one team, then the other team. You can't "give 15 minutes to start and join". 

I wonder if using 1 global time, then a short grace period to allow a team to forceready themselves for a minute (think similar to ESEA matches & .reportffw) would be better. (note that anyone on the team can forceready their full team)

**Comment by miped** [comment]
How about having two orthogonal features. Instead of changing the per-team one to a global one, we just add a global setting.

It will work like this: If it's set to 5 minutes, when the time is up, whichever team has the most time left on their ready timer wins by forfeit. Or alternatively, the match is just ended without a winner.

It's simple, easy to implement, and the two features complement each other nicely (For instance, you could set a 5 minute limit per team, and a global 10 minute limit. This would ensure that your game will start within 10 minutes in the absolute worst case, but you'd still get the right team getting punished if it doesn't.)

Also, it would allow people to use one or the other feature. Personally, we're not interested in the global one, since a match MUST end with a winner in a LAN tournament setting. So halving the time on the per-team one works fine for us.

**Comment by grenadecx** [comment]
The reason I reported this as a bug in the first place was because it wasn't obvious that this feature was suppose to work like this.

I still would like to add a global setting, something like @miped suggested would work. For me it makes sense to be able to enforce hardlimit on the time, which isn't really possible right now.

If that would be better suited, I could probably make a PR for this.

**Comment by splewis** [comment]
#370 should have addressed this now.
