### ISSUE TITLE
Detect player disconnect

### ISSUE THREAD

**Issue by gabrielfgularte** [splewis/get5#165]
If all players leave the game, it stays `live` and does not finish. On the first player return, the match throw a `round_end` event and the match goes back to the very first round after the knife with 0x0 score. Is this the expected behaviour?

If this is the expected behaviour, is it possible to intercept some disconnect player event? So we can track the players disconnect and/or reconnect actions, and that would be easy to advert, warn and punish the players who deserts.

Besides that, would be nice to have a cVar that finishes the game if the last player leaves, or to configure "what to do if any player disconnect". Things like pause game, end game, restart on reconnect, etc.

**Comment by splewis** [comment]
I haven't put much thought into what happens if everyone leaves a live match, so I'm not sure there's really any expected behavior. Server hibernation & csgo is... annoying.

I'd be fine with some basic behavior like:
- detecting if everyone left, and doing a match restore from the backup when someone came back.
- or ending the match

I guess a cvar for both, and a disabled option (and a forward for this as well).

That said... I don't think I'll get around to this soon.

**Comment by gabrielfgularte** [comment]
@splewis Thank you for your answer.

We need this for our project, so I took it upon myself to make something that could be a starting point. I'll submit a PR for you. Hope it helps.

Even if you don't plan on using it, I would be greatful if you could give me some feedback.
