### ISSUE TITLE
Map vote posted to API?

### ISSUE THREAD

**Issue by svencan** [splewis/get5#189]
Hello,

Is the map vote (map_pick / map_veto) posted to the API?

Thanks in advance,
Sven

**Comment by splewis** [comment]
I'm not sure what you mean by "the API".

You could mean 

1. the [plugin forwards](https://github.com/splewis/get5/blob/master/scripting/include/get5.inc)
2. the [event logs](https://github.com/splewis/get5/wiki/Event-logs), 
3. the [api plugin for the get5-web interface](https://github.com/splewis/get5/blob/master/scripting/get5_apistats.sp)

The answer to 1 & 2 is yes.

The answer to 3 is no, but that API is **only** meant as an implementation detail between the get5_apistats plugin and the get5-web interface anyway. Relying on it otherwise makes yourself liable to be broken by updates.
