### ISSUE TITLE
Simple Config issues

### ISSUE THREAD

**Issue by keeradfun** [splewis/get5#193]
Small Config changes required.
1) In get5/live.cfg  sv_deadtalk supposed to be set to "1".  Because if you set sv_deadtalk to "0", players cant communicate to their team members once they die in particular round.

2) In get5/warmup.cfg keep mp_autoteambalance to 0 and mp_limitteams to 0.because if one team tries to join the server before another team, whole team cant join unless other team members join.
(P.S. Sorry for bad english.)

**Comment by splewis** [comment]
I'll add mp_autoteambalance and mp_limitteams since there's no negatives from turning those off. I'm going to leave sv_deadtalk set to 0 though. 

The live/warmup configs are meant to be customized, so if you really want deadtalk, you can change it. Having it off is quite standard for competitive play so dead teammates can talk to each other in-game while dead, without the alive players having to hear them (since the entire team is generally in a 3rd party voice server).
