### ISSUE TITLE
[Feature Request] (Option to) Use mp_teamscore commands instead of mp_matchstat commands for GOTV display

### ISSUE THREAD

**Issue by AlthalusAvan** [splewis/get5#226]
In my opinion the commands: 

```
mp_teamscore_max
mp_teamscore_1
mp_teamscore_2
```

provide a much cleaner and more visually pleasing UI experience to display match scores to the user. I'd like to see an option to use these as opposed to the current mp_matchstat commands used, or see the system default to these where the match title isn't explicitly set.

You can see the difference here:
mp_matchstat (current system) commands display like this:
![516354540_preview_example_matchstat](https://user-images.githubusercontent.com/15961147/36031973-63b90c9a-0da4-11e8-8c01-09d2f45bd6a4.png)

mp_teamscore (proposed change) commands display like this: 
![516354540_preview_score](https://user-images.githubusercontent.com/15961147/36032016-85f1d904-0da4-11e8-9e83-81462d00fbe5.png)

The main argument for the mp_matchstat system is the "Map X of X" text providing clarity on how many maps have been played, but I don't personally think the loss of clarity is significant.

**Comment by Technoblazed** [comment]
As far as I’m aware, this is already a thing in BoX series

**Comment by AlthalusAvan** [comment]
Currently on my server it uses the mp_matchstat method exclusively even in
Best of series.

**Comment by Technoblazed** [comment]
What’s your plugin version?

**Comment by splewis** [comment]
1. get5 has set those cvars since 0.5.1
2. get5 will still use the mp_matchstat* cvars if you provide ``match_title`` or ``matchtext`` fields in your match config, but you they're discouraged
3. you got the order of your screenshots swapped

If those cvars aren't being set on version 0.5.1 or later then there's a bug, and I'd need more info (match config, version) to look into.
