### ISSUE TITLE
Testing the Plugin without "real players"

### ISSUE THREAD

**Issue by tloesch** [splewis/get5#285]
I want to run a match without real players except me.
The reason behind it is that i want to test the get5 configuration i made.
And in the future i also want to extend the plugin with new functionality.

I dont have real people who help me testing the stuff i have done.

@splewis @Technoblazed 
Maybe you can tell me how your workflow is when testing or developing a new feature.

**Comment by Technoblazed** [comment]
Dependent on the feature, I usually just stick a message in one of my discord’s and start a tenman up, it’s usually the easiest way

**Comment by pupsick** [comment]
Just find any community to post in or just create your own.
Btw, @Technoblazed you can ask any time for quick tests, if you want to. We have the opportunity to do this :)

**Comment by tloesch** [comment]
Thanks for the comments.
So there is no way to Test this Plugin without having some people helping you.

I Close this issue now.

**Comment by pupsick** [comment]
Just in case, like @Technoblazed said - you can easily  test some features, that isn't require the real match. just make some config just to run match and then test whatever you want during warmup period. :)

**Comment by splewis** [comment]
> So there is no way to Test this Plugin without having some people helping you.

That depends what you're testing. 

For most testing I typically use 2 clients (aka my desktop and laptop).

Unit tests aren't really feasible in sourcemod plugins, especially since most the stuff that is worth testing is interactions with the game server itself.

There actually is a very limited set of tests in get5 (https://github.com/splewis/get5/blob/master/scripting/get5/tests.sp), but they're not really that useful or automatically run.
