### ISSUE TITLE
How can I connect to GOTV server?

### ISSUE THREAD

**Issue by snarxcsgo** [splewis/get5#299]
How can I connect to GOTV server? - I would like during the games, people from outside the tournament could watch all matches.

**Comment by TandelK** [comment]
It depends on your server cfg , Most of the commands are directly included in Get5 and Game Commands like tv_enable 1 and more options. You can get most of the GOTV CVARs from CS:GO Official CVAR List located : https://developer.valvesoftware.com/wiki/List_of_CS:GO_Cvars

If you use find and find for tv_ commands which will give all the information

tv_enable 1 will enable GOTV on the server,
now as you request that people from Outside tournament should be able to connect to the GOTV than you have to use 
tv_advertise_watchable 1 


Most of the Common CVARs used for all the major GOTV i am mentioning below


> tv_enable  1
tv_enable1 0 [There are 2 GOTV Spectators from now on One has 90 Seconds delay other can have 100 Seconds delay giving 2 different views at the same time but Public can connect only one GOTV at a time so not really required , Good for Live Streaming and Casting the Match ]
tv_advertise_watchable 1
tv_autorecord  1   [Note : This command will auto record all the Demos' automatically to CSGO Folder with .dem file] 
tv_delaymapchange 1  [Note : This command is optional but required for Tournament as GOTV will be showing 90 Seconds behind the real Game time so when the map changes people in GOTV will not be able to see last 90 Seconds , in order to prevent that , this command is used where server will force 90 Seconds delay for next Map]
tv_maxclients 128 [Number of GOTV Clients can connect]
tv_maxrate 0 [set to 0 for Unlimited Rate for best Performance] 
tv_name "This will be GOTV Bot Name inside the server" 
tv_port "GOTV Port" 
tv_relaytextchat "0" "This will not send in game players messages to GOTV"  | If want to send set to 1
tv_relayvoice "0" This will not send in Game Players Voice to GOTV | If want to send set to 1 , Consumes more Bandwidth 
tv_snapshotrate 128 We keep this to 128 for forcing the GOTV to run at 128 Tick because by default it will run at 32 Tick and if running Server on 128 Tick and GOTV on 32 Tick it will be totally desync view]
tv_title "GOTV Title for example Fnatic vs North"

**Comment by splewis** [comment]
What TandelK said above - it's completely unrelated to using get5.
