### ISSUE TITLE
OverTime.

### ISSUE THREAD

**Issue by abdulsami34** [splewis/get5#305]
Hello, This is not a issue, this is just a general question.

I'm basically using get5 for normal scrims now. I wanted to know if the overtime mode is enabled by default?

Or do i have to change the command to mp_overtime etc to 1

**Comment by splewis** [comment]
get5 executes whatever commands you have in cfg/get5/live.cfg.

By default that is what is in https://github.com/splewis/get5/blob/master/cfg/get5/live.cfg.

If you are using the get5_scrim command the cvars in you scrim template are also set, by default those are in https://github.com/splewis/get5/blob/master/configs/get5/scrim_template.cfg#L33

overtime is disabled there, mainly because mp_match_can_clinch is set.
