### ISSUE TITLE
Feature Request - Auto Pause match in middle of Client Disconnect

### ISSUE THREAD

**Issue by TandelK** [splewis/get5#312]
A recent new CSGO CVar was released i think which basically detects whenever in a competitive match a player gets disconnected the game will auto pause 

"sv_matchpause_auto_5v5" = "1"

**Comment by Technoblazed** [comment]
I feel like this should be left out of the config by default, it’s a cool cvar but probably something that should be added by the user on a per case basis.

**Comment by splewis** [comment]
How sv_matchpause_auto_5v5 interacts with the builtin pause system is likely something that most users could find confusing, so I don't intend on adding it to the default configs (even disabled).

In general, the idea behind sv_matchpause_auto_5v5 is okay, but it's a confusing cvar since issuing a ``mp_unpause_match`` will not actually cancel a pause with ``sv_matchpause_auto_5v5 1`` (at least the last time I checked). The ``sv_matchpause_auto_5v5`` cvar is not recent, I used it over 2 years ago.
