### ISSUE TITLE
How to enable the MP5

### ISSUE THREAD

**Issue by cuexit** [splewis/get5#319]
Hi!

I was wondering how i activate the mp5 in get5 cause i can't find it anywhere where to do this. I looked trough every file and can't seem to find it.

Kin regards,

Cuexit

**Comment by TandelK** [comment]
check your gamemode_competitive_server.cfg file where there should be a cvar in the end which weapon to not use in this mode. Remove that CVar

**Comment by Technoblazed** [comment]
Make sure you have `mp_items_prohibited ""` somewhere in your config.

**Comment by cuexit** [comment]
@Technoblazed Thank you i will try this out and see if this works.

**Comment by cuexit** [comment]
@Technoblazed its already the file but when i go ingame and check it it says 

> mp_items_prohibited 23 

So do i need to update get5 because i used have it before the mp5 was released so is there a file i need then?

**Comment by Technoblazed** [comment]
You're setting it in another file, this issue isn't anything to do with get5. Check all of your config files.

**Comment by cuexit** [comment]
Nvm found a file where the command blocked the mp by default removed the 23/mp5-sd and it works

**Comment by TandelK** [comment]
Well it says empty because none of the CSGO Server Operators really create gamemode_mode_server.cfg files which are very much important because when you will validate Game files anytime the file with gamemode_mode.cfg will get overwrite by the server itself. This will cause the error again. I would really recommend everyone to create the files with names of _server.cfg which will never get edited when there is server validation.
