### ISSUE TITLE
2 coaches reading their team messages

### ISSUE THREAD

**Issue by stepharvey** [splewis/get5#332]
Hello! 

I know it is a long shot but we have 2 coaches on the same team in our practice and while the coaches can hear each other ingame, they cannot see each other's team messages.

Would love to get that feature! Thank you!

Also btw GET5 is awesome and really usefull for our team 💃 really good job!

**Comment by splewis** [comment]
Are you currently using the [csgo_hearcoach](https://github.com/splewis/sm-misc/blob/master/scripting/csgo_hearcoach.sp) plugin? (if you type ``sm plugins`` in console you'd see it listed as 'Coach deadtalk fix')

I think the only reason the coaches (and people in deadtalk) can hear each other is that plugin, so maybe I should just update that plugin to fix that. 

I'll consider actually merging that functionality into get5 anyway though. I didn't put it in get5 originally since I assumed Valve would fix it, but here we are...

**Comment by stepharvey** [comment]
You are right, I am using your pluggin! Oops! Totally forgot it wasn't in
get5 but in the hear coach pluggin! I know it's a weird request cause most
teams probably don't have 2 coaches but it would definitely help us. Let me
know if you end up adding that! Thank you so much for your amazing work!

**Comment by splewis** [comment]
This [change](https://github.com/splewis/sm-misc/commit/59866baea01f8168745e7ef68f967171829a3793) should make coaches see each other's chat (though it's untested).

You can get an updated csgo_hearcoach plugin at http://dl.whiffcity.com/plugins/sm-misc/ or from downloading a zip at https://ci.splewis.net/job/sm-misc/19/.

I'll continue thinking about if I want to add the coach deadtalk fix in get5 itself. Ideally my goal is that get5+practicemode should be the only plugins any team needs on a practice/scrim server.

**Comment by stepharvey** [comment]
Hey!

Just tested it, it works!!! Thank you so much for this! So fast and
effective! Love your work!

*stepharvey*
*daily updates on Twitter <http://twitter.com/missharvey> | Instagram
<http://instagram.com/stepharvey> | YouTube
<http://youtube.com/c/missharvey> | Facebook
<http://facebook.com/harvinator>  *\ (•◡•) /
