### ISSUE TITLE
Demo files

### ISSUE THREAD

**Issue by ckilian1** [splewis/get5#333]
I read the section for demos, but I still don’t completely get it. Where do I find the demo file. Also at the bottom where do I put that code.

**Comment by splewis** [comment]
I updated the wiki page.

The demo files are under the root `csgo` directory. This doesn't really have anything to do with get5, they are always there.

> Also at the bottom where do I put that code. 

In your own plugin that you create, if you want to do something with that file automatically.

**Comment by ckilian1** [comment]
Ight do I need to make my own id or is it automatic?

**Comment by splewis** [comment]
What id are you referring to?

**Comment by ckilian1** [comment]
The game id

**Comment by splewis** [comment]
I assume you mean the match id set in the get5 match configs. 

The only time one is automatically created is when you're using the get5_mysqlstats plugin: https://github.com/splewis/get5#get5_mysqlstats

Otherwise you should usually set it yourself, if you care about it being unique (you might not, I don't know).
