### ISSUE TITLE
get5_apistats suggestions

### ISSUE THREAD

**Issue by mgjuhler** [splewis/get5#369]
I have a feature request for get5_apistats, server log.

I have spent a couple of hours figuring out how get5_apistats works, i am going to make my own web interface. And I would like to request a match log, like https://pastebin.com/TKh3yUTd

This would be really nice so not only the admins but also the participants can "see" how it goes in the match.

- match config loadet, game ready.
- player join game.
- player ready/team ready.
- knife start / knife end.
- stay/swap status.
- ! ingame say commands
- map veto and veto status.
- game live.
- player kills, bomb plants and like.
- round status.

Thanks for a great alternative to ebot :)

**Comment by PhlexPlexico** [comment]
Hey! I suggest being wary of using apistats, as the README states
> Considering starting from those plugin and making any changes you want (forking the get5 plugin itself is strongly discouraged; but just making another plugin using the get5 plugin api like get5_apistats does is encouraged).

So I think if you wanted these feature implementations, it would be best to start on them, and then maybe even make a PR so they can be added back into the baseline. I think the apistats was created more for a building block, than something to be actively worked on, but I could be wrong, it's just how I inferred it. However, it's not too difficult to add to the plugin, and the logs get5 produces makes it relatively easy to extract data from (key-value pairs) and read into your web-panel to make it presentable.

**Comment by mgjuhler** [comment]
> Hey! I suggest being wary of using apistats, as the README states
> 
> > Considering starting from those plugin and making any changes you want (forking the get5 plugin itself is strongly discouraged; but just making another plugin using the get5 plugin api like get5_apistats does is encouraged).
> 
> So I think if you wanted these feature implementations, it would be best to start on them, and then maybe even make a PR so they can be added back into the baseline. I think the apistats was created more for a building block, than something to be actively worked on, but I could be wrong, it's just how I inferred it. However, it's not too difficult to add to the plugin, and the logs get5 produces makes it relatively easy to extract data from (key-value pairs) and read into your web-panel to make it presentable.

Hi PhlexPlexico, thanks for your reply.

I have absolutely no experience in programming the sourcemod plugins, I have looked at the source code but cannot find the head and tail in it. I usually program php but this is built up in a different way than I am used to from php.

There is a huge potential in get5 but there are still many features missing before get5 is a real alternative to ebot.

a larger lan event would never use get5 via rcon cmd as there is too much work in it. That is why I work on a web interface that will make things easier and far more manageable. 

one of the things get5 lacks is that an admin can't see what the status on a match is. As of now get5 first make an api call when the game is started, ie after the knife/veto round. There is no info on whether there are any people who are joining the server, whether knife/veto has started or who has won and whether or not they change sides. It is a huge problem as you as an admin at an event have to keep track of many matches and if you do not have an overview of it then you have to check every single match via rcon or the like to get a status. 

I really hope that someone has the time to make logging in get5_apistats. or just make a few examples of how a couple of the things can be pulled out of the server and then I'd like to give it a try if I can do the rest of it.

**Comment by PhlexPlexico** [comment]
So just a heads up , you know that there is a repository (while experimental, usable) that splewis did create, which is the get5-webpanel. It is used in conjunction with the get5_apistats plugin. While it is extremely rough and unsupported, there are a few people who have forked it to make it suit their needs (me included). It's built on Flask, which uses python and I found fairly easy to develop from.

I agree that the web front end is a bit.... bare, to say the least, there is potential on that. I know in the README as well, it is recommended that you can read from get5 logs, and use a listener on the log files (which give _tons_ of information, I'll upload one when I have the chance here), and examine the events, or build off the apistats plugin (which I've done a minor amount, and all the forwards and events you can go off of are based in the wiki). 

During matches, you can see the current score, match start time, end time, if a team forfeited, etc, as well as send commands all via the webpanel, as previously mentioned. I'm not vouching for it, as it does say it's unsupported, and filled with bugs, but that is one example of what you could possibly look towards and build off of. 

Since API Stats works with SteamWorks HTTP status, you can send requests to a web server that is listening, much like what is done in the [match_check](https://github.com/splewis/get5-web/blob/master/get5/api.py#L34) in the get5-web panel. Looking into the source for this, I agree and is daunting at the start without a doubt. 

> I really hope that someone has the time to make logging in get5_apistats. or just make a few examples of how a couple of the things can be pulled out of the server and then I'd like to give it a try if I can do the rest of it.

Since logging is done via get5, you can definitely do what eBot does and attach a listener and read from the log file that get5 produces. 

But yeah, the groundwork is there and I'm sure someone could probably make an identical panel to eBot  that uses the get5 config even, and sends off a JSON formatted config to get5 (which can be done without apistats). 

And don't worry, I've never done Sourcemod programming either, and I'm still new to it. Once you get your head wrapped around it, it becomes a little bit easier, but even then I still try and implement features on the web-side as much as possible and just work with what I have from the plugin!

**Comment by mgjuhler** [comment]
what i do is get5 get also starting point in get5_apistats. however, i have chosen to code everything from scratch but have looked at how things are used in get5 web. I currently have almost the entire admin section finished and have got the api part to work so I get data from the match. today i must have looked at the match section where i generate match config and like.

**Comment by splewis** [comment]
I don't expect making any changes to get5_apistats. It's more likely I remove it and move it to the get5-web repo. It's not meant to implement a public API - just an example of how to do things (much like the get5-web is just meant as an example, although too many people apparently use it...). 

If there's useful general features (e.g. additional events in the event logging system) I'm happy to add them, but I don't want to create a larger API for match stats *just so get5_apistats* can call it. I'd prefer to keep that to someone actually creating their own web interface/service.
