### ISSUE TITLE
[Question] Add match_id from config on Stats object

### ISSUE THREAD

**Issue by victorbuttner** [splewis/get5#416]
There is a possibility to add the matchID (sent in config) to the Status object ? I'm trying to find when the match is finished using mysql_stats but the custom match_id is not saved  into this table.

**Comment by splewis** [comment]
What do you mean by "status object"? And which table are you referring to? The matchid is part of the primary key in the tables: https://github.com/splewis/get5/blob/master/misc/import_stats.sql

**Comment by victorbuttner** [comment]
I want save an id like 'example_match' on the stats match table , not only depend of the id from the table

**Comment by victorbuttner** [comment]
On the match config file is posible to use custom ids with strings

**Comment by splewis** [comment]
Yeah, the mysql stats plugin requires integer matchids, but get5 generally doesn't. You'd have to do something custom for your case, like change the schema and tweak the get5_mysqlstats plugin.

get5_mysqlstats is basically *meant* to be forked rather than fit most people's use cases, so I'd do that. I'd consider changing get5_mysqlstats, but the schema uses integer ids so that's a probably a bad idea for compatibility reasons.

**Comment by victorbuttner** [comment]
Thank you for the reply, a custom id or just match name will be helpful to create and identify matches dynamc.
Wich method Will return the match id (string) that was set in the match config ?
In theory I Just have to change the insert in the table with this property

**Comment by splewis** [comment]
> Wich method Will return the match id (string) that was set in the match config ?

https://github.com/splewis/get5/blob/master/scripting/include/get5.inc#L132

> In theory I Just have to change the insert in the table with this property

Pretty much.
