### ISSUE TITLE
Questions about spectators

### ISSUE THREAD

**Issue by Parad0x0001** [splewis/get5#444]
Is there any way to force players in the match to their teams, yet still allow anyone to join and force the non-players to spectator rather than saying "You are not a player in this match"?

**Comment by splewis** [comment]
https://github.com/splewis/get5#match-schema

You can add a "spectators" section in addition to a "team1" / "team2" section (it should only contain the "players" & "name" entries, though).

**Comment by Parad0x0001** [comment]
I saw this, but I can only set the steamid's of people I know (staff members), and the plugin still kicks random players who join but aren't in the current game

**Comment by TandelK** [comment]
The reason why this restrictions are kept because people cannot join in middle of the tournaments and give all the informations to players. If you want everyone to join the server, you will have to disable check auths command that is `"get5_check_auths" = "1" ` , This cvar can be used in 2 different locations for making it by default it will be in cfg/sourcemod/get5.cfg section for this cvar where it can become default for all the matches or if you want to use it for specific matches you can use them in get5 match config file in cvars section of the match config file. 


[NOTE]  Using the above command will also disable Steam ID based Auto Team Join thing which will break the Competitive mode set by Get5 so any player joining server can join any team they want to including in middle of the matches which i think no one wants to use it. 

If you have Steam ID of that specific person you want to add to Spectators please use below command

`get5_addplayer "STEAMID" "team1|team2|spec"`

So for you it will be `get5_addplayer "STEAMID" "spec" `  , make sure to include  `""` with the command in given area.

**Comment by saintplay** [comment]
Excuse my dumb question, but why don't you use GOTV instead?

**Comment by Parad0x0001** [comment]
Thankyou for explaining how the plugin works, I guess what I was trying to accomplish isnt possible so I'll have to look for another solution.

Regarding to the gotv @saintplay , I have no idea how to set that up, however if you'd be interested in giving me some documentation or help about how to do it feel free to add me on discord: Parad0x#0001
