### ISSUE TITLE
Feature request: ability to disable "unable to get steamid" messages in the console

### ISSUE THREAD

**Issue by JustinBenedick** [splewis/get5#448]
I am currently working building a lan only tournament server config. The issue I am getting is that since I have authenication disabled I am getting spammed with "[get5] Unable to authenticate steamid" in the console and logs. Is there a way to disable to those messages?

**Comment by MikkelDK** [comment]
Try this:

sv_lan 0 and Set Steam GLST and set +net_public_add to LAN IP

**Comment by JustinBenedick** [comment]
I'll give that a shot but I am not really comfortable using sv_lan 0 on in my situation

**Comment by tloesch** [comment]
You can disable the auth. Function with  get5_check_auths 0.

**Comment by TandelK** [comment]
The reason you get this error is because Steam based condition is added on server for Online Tournaments where Players are assigned properly to their teams respectively. You might already know about it , you can modify the code a bit for yourself. You can add condition checking if sv_lan is 1 , disable Steam based authentication in that code. I would still not recommend it as sv_lan setting to 1 also disables VAC Mode .

**Comment by splewis** [comment]
With `get5_check_auths 0` you shouldn't see the messages. `sv_lan` is up to you, but I don't find that using get5 adds that much value without any authentication happening.

**Comment by JustinBenedick** [comment]
I did some tweaks to my server configs and ran another test, its not as bad now. The thing Is that my tournies would be in a lan environment so I am not worried about authentication. I am thinking that my problem was due to me using bots for testing.
