### ISSUE TITLE
Forfeit problem

### ISSUE THREAD

**Issue by eevyy762** [splewis/get5#478]
Hello forfeit when the data is not going to the site.

**Comment by splewis** [comment]
Please fill the issue template out if you want support:

If making a feature request, you should delete all the pre-filled text here.
If reporting a bug, fill in the following sections:

### Expected behavior



### Actual behavior



### Steps to reproduce

Please note that "latest" is NOT a version! See https://github.com/splewis/get5/wiki/Debugging-help#finding-get5-version if you need help finding these. Adding the output file produced by ``get5_debuginfo`` is extremely helpful.

- Plugin version:
- Sourcemod version:
- Steps to reproduce (please be specific):
