### ISSUE TITLE
Score reporting bug

### ISSUE THREAD

**Issue by AzuuraD** [splewis/get5#51]
If reporting a bug, fill in the following sections:

### Expected behavior
After a round is won, show [Get5] Teamname1 1 - 1 Teamname2

### Actual behavior
http://i.imgur.com/9XWDuAe.jpg

### Steps to reproduce
- Plugin version: 210
- Sourcemod version: SourceMod Version: 1.8.0.5916
Start a game, 5vs5. play a round

**Comment by splewis** [comment]
This probably has more to do with the CS:GO update from August 5th breaking the CS_Set/GetTeamScore methods. It required a gamedata update (see https://github.com/alliedmodders/sourcemod/commit/51a6b9ce30de78f7a78b79739d1f911795b87604).

Have you tried restarting your server again since then (that is when sourcemod automatically updates gamedata files)?

**Comment by AzuuraD** [comment]
Yes, the server is restarted before every match, so i'm not 100% sure why the gamedata files havent updated

**Comment by splewis** [comment]
Have you checked if they're updated? You should compare the commit I posted and the game server's ``addons/sourcemod/gamedata/sm-cstrike.games/game.csgo.txt``.

**Comment by AzuuraD** [comment]
I've updated sourcemod manually now,  will see if it solved the problem when I next can

---- On Sat, 13 Aug 2016 02:20:57 +0000 notifications@github.com wrote ----

Have you checked if they're updated? You should compare the commit I posted and the game server's addons/sourcemod/gamedata/sm-cstrike.games/game.csgo.txt.

**Comment by AzuuraD** [comment]
Yep this fixed it, thanks :)
