### ISSUE TITLE
print damage by web panel

### ISSUE THREAD

**Issue by kapselele** [splewis/get5#591]
If making a feature request, you should delete all the pre-filled text here.
If reporting a bug, fill in the following sections:

### Actual behavior
I want to change the get5_print_damage  to 1 (default is 0) in cfg/sourcemod/get5.cfg.
In console when i type this command  with rcon i can see value: 1 but it's not working on matches. Am i doing something wrong? Let me know, bcs i really like the web panel.
P.S.
 Can you Splewis add dark mode and custom logo in panel please?

### Steps to reproduce

Please note that "latest" is NOT a version! See https://github.com/splewis/get5/wiki/Debugging-help#finding-get5-version if you need help finding these. Adding the output file produced by ``get5_debuginfo`` is extremely helpful.

- Plugin version: 0.7.1
- Sourcemod version: 1.10.0.6492
- Steps to reproduce (please be specific):

**Comment by Drarig29** [comment]
I believe you are misunderstanding the purpose of the cvar `get5_print_damage`. This cvar isn't supposed to display anything in the web panel.

It only prints a damage report in the in-game chat.

And by the way, the webpanel isn't maintained anymore, so don't wait for any additions 😉

**Comment by Apfelwurm** [comment]
Like @Drarig29 already mentioned, the readme of the webpanel states:

> : YOU SHOULD NOT USE THIS. IT HAS BUGS. IT HAS NO SUPPORT. The get5 plugin itself is supported - this webpanel itself has NO support. If you want a working webpanel for get5, look elsewhere or develop your own.

Therefore you would have to fork the webpanel and do custom stuff on your own one if you want. To add the damage on the webpanel you would have to add the needed capabilities also there and also fork the get5_apistats plugin which is here in the repo and add this feature there. Perhaps you also would have to do a PR to get5 since i don't have in mind if the damage is stored as long as it would be necessary to be accessed by the apistats plugin itself.

**Comment by splewis** [comment]
> Can you Splewis add dark mode and custom logo in panel please?

PRs welcome for the web panel. You really shouldn't be using it, though, as mentioned above.

`get5_print_damage` indeed has nothing to do with the web panel.
