### ISSUE TITLE
Question / Request for explanation: Fork of get5_apistats

### ISSUE THREAD

**Issue by Apfelwurm** [splewis/get5#592]
Hi! Like the readme suggests, we want to build a own version of the get5_apistats plugin to work with our used website system eventula. Since the apistats plugin includes a few things from the include and the get5 folder and the readme tells me "forking the get5 plugin itself is strongly discouraged" i have asked myself some questions.

Should we work with git submodules to build the whole thing and not have the whole get5 code in our repo? If thats the case, we have to put it in a subfolder of our repo and therefore the include paths would be different. Since i don't really understand why the release versions of any sourcemod plugin have the smx files and the whole scripting files in it would it cause problems when the include paths are different here?

Do we need to hack something for our build process to move the needed includes to the right place for building the plugin so it can afterwards work with a standard get5 installation?

Am i thinking to complicated here and we don't need to care for the includes in the build stage at all (i dont think so)?

The alternative would be to fork the whole get5 repo and leave all the other parts untouched but then we have to pr all the future changes from get5 in there, which is also not nice since we only want to develop the plugin itself there.

Any help/explanation is very much appreciated!

**Comment by Drarig29** [comment]
Here is a plugin you could get inspiration from:

https://github.com/yannickgloster/get5_eventapi

I think he uses the default SourcePawn compiler to [build the plugin](https://wiki.alliedmods.net/Compiling_SourceMod_Plugins) because there is no `smbuild` file in his repo.

(The `smbuild` file is the configuration file for [sm-builder] (https://github.com/splewis/sm-builder).)

By the way, there is a Discord server for this plugin, maybe you could ask the creator 😉

**Comment by yannickgloster** [comment]
That is actually my plugin and yes I compiled it using `spcomp`. 

[get5_eventapi](https://github.com/yannickgloster/get5_eventapi) is heavily based on get5_apistats so what I did was I copied over all the code relevant to get5_apistats (includes and libraries) and then modified the code as I needed. What my code does specifically is it sends every get5 event to a specific endpoint instead of routing it depending on match. It just made more sense for my project, [discord-10man](https://github.com/yannickgloster/discord-10man) which is a lightweight pug management system for small communities and groups of friends.

I made sure to credit @splewis in the repository and the code itself.

**Comment by Apfelwurm** [comment]
Thanks @all for the input. I've decided to make it automatable, so i've worked with a submodule folder of get5 which gets updated every time when building it with docker (in the dockerrunscript). If anyone needs to use this in the future, feel free to use it :) https://github.com/Lan2Play/get5_eventula_apistats/tree/8875400be080523ede94c2109473ae9d351e5e8e
