### ISSUE TITLE
Wenpanel wont record all the players stats 

### ISSUE THREAD

**Issue by GTAmama16** [splewis/get5#622]
As you can see im not sure why the webpanel arent recording all the players stats, it only record few players stats
can anyone give me a hand ?

thanks 
![螢幕擷取畫面 (23)](https://user-images.githubusercontent.com/31006601/105057675-6dee2680-5ab0-11eb-9f52-5927c6b194d6.png)

**Comment by PhlexPlexico** [comment]
Hi, I think this might be better to create an issue on the [get5-web](https://github.com/splewis/get5-web) repository. But, by the looks of it its due to the database character set not being set to utf8mb4, as seen in previous issues located here:

https://github.com/splewis/get5-web/issues/101
https://github.com/splewis/get5-web/issues/140
https://github.com/splewis/get5-web/issues/159

I found your matches/teams on that web panel, and it appears that 8/10 players have characters in their name that are not supported, so they fail to insert. If they change their names on steam to not include any special characters, they should start recording.

**Comment by GTAmama16** [comment]
> Hi, I think this might be better to create an issue on the [get5-web](https://github.com/splewis/get5-web) repository. But, by the looks of it its due to the database character set not being set to utf8mb4, as seen in previous issues located here:
> 
> [splewis/get5-web#101](https://github.com/splewis/get5-web/issues/101)
> [splewis/get5-web#140](https://github.com/splewis/get5-web/issues/140)
> [splewis/get5-web#159](https://github.com/splewis/get5-web/issues/159)
> 
> I found your matches/teams on that web panel, and it appears that 8/10 players have characters in their name that are not supported, so they fail to insert. If they change their names on steam to not include any special characters, they should start recording.

i see, so if i ask all the players just change their name to English only and it should be fixed ?

**Comment by nickdnk** [comment]
You may need to set `utf8mb4` character encoding in your tables and on the connection to the database. See https://github.com/splewis/get5/pull/608/files#diff-c4154d12ae064f557e3b359f5861f53f7f998ea3945efa06c75eda81429af374R64 and the changes to the MySQL tables made in that PR as well.

**Comment by GTAmama16** [comment]
> You may need to set `utf8mb4` character encoding in your tables and on the connection to the database. See https://github.com/splewis/get5/pull/608/files#diff-c4154d12ae064f557e3b359f5861f53f7f998ea3945efa06c75eda81429af374R64 and the changes to the MySQL tables made in that PR as well.

thanks man its fixed now 👍
