### ISSUE TITLE
Add countdown time for team to connect/ready up

### ISSUE THREAD

**Issue by splewis** [splewis/get5#7]
If they don't connect/ready in time, the match ends (and the proper forwards fire).

Might mean there should be an additional forward: ``Get5_OnFailToStart`` with booleans for each match team if they failed to ready up/connect.

**Comment by bgilb5** [comment]
I've been doing some research on this and it doesn't look like there is anyway to hook in to warm up end (to use the built in competitive warmup). I was going to try counting the number of round_ends to see if warmup was ending, but round_end doesn't even fire at the end of the warmup. The only way I can think of is to have the infinite warmup, then have a custom timer that runs and handles the warmup ending before everyone joins and ends the match if they don't. It could print to console every minute or so and the last 10 seconds. What do you think?

**Comment by splewis** [comment]
You're right that the builtin warmup is very tricky to deal with. I do still think it should be possible to use, though.

Hooking round_start and checking if no longer in the warmup phase (InWarmup() is now false, but the plugin game state has it in warmup still) could potentially work.

**Comment by bgilb5** [comment]
Yeah that's a good idea, I wasn't sure if it would be weird since they
might spawn. But I'm guessing round_start is fast enough if you just kicked
them in that check.

I also checked if it was possible to hook into the warmup messages that get
posted in the chat. Right now it says something like ">> Warming ending
soon and match will be starting" every couple seconds and ">> Warmup
ending, match is starting" when warmup ends. It'd be nice to remove those
completely. Not sure if its possible. I tried to see if you can hook
PrintClientMessageToAll

**Comment by bgilb5** [comment]
What you said kinda works, but I can only get rid of some of the messagessent . I can't get rid of the "MATCH STARTING IN X" larger banner messages. I can hook TextMsg to get rid of those 2 warm up match lines (since they're server chat messages). Also there is a hook for the "WARMUP ENDING" message so maybe that can be used to detect warm up ending and the end the match there so it never shows the MATCH STARTING message. Unless there is a usermessage for those banner messages in the center.

**Comment by splewis** [comment]
I don't see why you would need to get rid of any of the messages.

**Comment by bgilb5** [comment]
It says "Match will start when warmup has ended." Then it says "Match
starting in..." Seems kind of misleading

**Comment by saintplay** [comment]
I know this issues is old,

but does this mean that get5 is not using the builtin warmup, right?

Is there any way to show "WARMUP" in the center of the screen like the builtin warmup?

**Comment by splewis** [comment]
> but does this mean that get5 is not using the builtin warmup, right?

It does - except in some weird edge cases (for example, an admin / another plugin can certainly type `mp_warmup_end` in console and get5 won't try to start the warmup again).

**Comment by saintplay** [comment]
So, is it possible to show message like "Warmup %s left"?
