### ISSUE TITLE
[BUG] "You can only change coaching position during warmup."

### ISSUE THREAD

**Issue by datemike972** [splewis/get5#700]
### Expected behavior
During a match one of the coach disconnected and when he tried go to coach again, It didn't worked for him and in the console log was showing "You can only change coaching position during warmup.".

We tried everything, from restart to round backup - nothing have worked.

the only solution we found for it is to enable warmup, coach enters and do !coach and then round backup.
it's ok but we have GSI Data system and all of this process is hurting it.

Is there any solution for this?

Thanks

**Comment by WardPearce** [comment]
Attempted to recreate the issue without Get5 using the plugin below, appears to move people to coach fine mid match and after reconnecting. What makes me think its a server configuration issue or something odd with Get5.
```c
#include <sdkhooks>
#include <sdktools>
#include <sourcemod>
#include <cstrike>
#pragma newdecls required
#pragma semicolon 1


public Plugin myinfo = {
	name = "Test plugin",
	author = "",
	description = "",
	version = "1.0.0",
	url = "https://github.com"
};


public void OnPluginStart() {
	RegConsoleCmd("sm_coach", Command_Coach, "Enters coach mode");
}

stock bool InWarmup() {
  return GameRules_GetProp("m_bWarmupPeriod") != 0;
}

stock bool InFreezeTime() {
  return GameRules_GetProp("m_bFreezePeriod") != 0;
}

stock void UpdateCoachTarget(int client, int csTeam) {
  SetEntProp(client, Prop_Send, "m_iCoachingTeam", csTeam);
}

public Action Command_Coach(int client, int args) {
	if (!InWarmup() && !InFreezeTime()) {
		LogMessage("Running SetProp");

		ChangeClientTeam(client, CS_TEAM_SPECTATOR);
		UpdateCoachTarget(client, 2);
	}
	return Plugin_Stop;
}
```

**Comment by kubo6472** [comment]
@WardPearce FWIW here are all the instances of making someone coach in the get5 code.

https://github.com/splewis/get5/blob/2b3e3d9ec883e09a86023c6f015db9b2178428a5/scripting/get5/teamlogic.sp

https://github.com/splewis/get5/blob/43b7f3d86c1e6978c7b01ad20f06247279b1cc9e/scripting/get5/util.sp

https://github.com/splewis/get5/blob/2b3e3d9ec883e09a86023c6f015db9b2178428a5/scripting/get5/readysystem.sp

https://github.com/splewis/get5/blob/43b7f3d86c1e6978c7b01ad20f06247279b1cc9e/scripting/get5/stats.sp

https://github.com/splewis/get5/blob/43b7f3d86c1e6978c7b01ad20f06247279b1cc9e/scripting/get5/matchconfig.sp

I'm very much beginner with sourcepawn, so I hope that someone a bit more experienced can make a sense of that. Thanks for your code snippet, yet to test it, since we're too using GSI to do some number magic, and LHM breaks things like round history when backups are being restored, so, yeah, help appreciated.
