### ISSUE TITLE
Add an option to not cap damage at 100

### ISSUE THREAD

**Issue by GekasD** [splewis/get5#707]
Why is this even a thing in the first place? it feels like the current behavior should be optional and turned off by default, or at least have a convar to disable it. I can do a PR to implement this if  you think its worth being added.

**Comment by nickdnk** [comment]
Why would you need this information? It's meaningless. I assume you would only want this to apply to the damage report at each round end, because the actual damage dealt is a metric for your impact and is always capped at 100, even in the official game. You can see this in the new premier matchmaking where the column called Damage is on the scoreboard. It does not give you 450 damage if you headshot someone with an AWP.

**Comment by rpkaul** [comment]
@nickdnk I agree its not that important to see total given damage but if its possible to see more information then i love to see that, its fun to see how much damage we did last round , what was the total damage on 1 player. thats the main reason i dont want to cap this .

**Comment by nickdnk** [comment]
Excess damage doesn't count towards ADR or damage given. I'd argue it makes things more confusing and inconsistent when taking the other stats we collect into consideraton.

**Comment by nickdnk** [comment]
Add in https://github.com/splewis/get5/pull/736.

**Comment by stalsus** [comment]
I'm glad this is added, but I still believe it should also be included in the stat tracking, kills * 100 is useless in my opinion.

**Comment by nickdnk** [comment]
> I'm glad this is added, but I still believe it should also be included in the stat tracking.

Nowhere else is damaged tracked like this. It gives a completely skewed impression of damage given across multiple rounds.

**Comment by stalsus** [comment]
Fair enough, thanks for adding this 👍🏻
