### ISSUE TITLE
Recognise BOTs as clients for teamname?

### ISSUE THREAD

**Issue by Renrael2022** [splewis/get5#740]
_How do i make get5 recognise BOTs as clients, so it can change the teamname?
example : team_chalamet vs team_johndoe, 
but it instead goes to the default name._

### Expected behavior

![expected](https://user-images.githubusercontent.com/98244712/153408062-05833b42-4319-4e45-90b9-9b53a650ee61.png)

### Actual behavior

![actual](https://user-images.githubusercontent.com/98244712/153408065-ffce9ba3-e47a-4743-ad61-4470d139137c.png)

### Steps to reproduce
_Turn on server using csgosl.
Get in a team.
Type !get5
Click 2. Create match with current players_

- Plugin version: 0.7.1
- Sourcemod version: 1.11.0.6851

**Comment by nickdnk** [comment]
Hello

I don't think we can really support bots since they cannot be identified via Steam ID. Also version 0.9 won't support any stat collection for bots.

Get5 is not really designed to be used with bots to be honest.

**Comment by Renrael2022** [comment]
> I don't think we can really support bots since they cannot be identified via Steam ID

But what if the bots have Steam IDs, like a fake client?

https://github.com/manicogaming/CSGOBetterBots/blob/10b9973247933bb4d86408ba095cf2631a647def/addons/sourcemod/scripting/bot_steamids.sp

**Comment by nickdnk** [comment]
Yeah, that's not something that's going to work. Get5 is not designed for bots. It's designed for 5v5 games with full teams. You should probably use PugSetup or something similar for this situation.

Also in the readme for that project: **In here there are some plugins that I personally edited to add the features of those plugins to the BOTs. I'm using these edited plugins on a Local Server because on a public server I'll get a Token ban.** - this kind of disqualifies support for this situation.
