### ISSUE TITLE
Process for Bo2 ?

### ISSUE THREAD

**Issue by Iwhite67** [splewis/get5#747]
Hello, i have read some topic here, i don't understand what exactly i put in map to win ?

Bo1 : maps_to_win 1
Bo2 : ?
Bo3 : 2
Bo5 : 3
Bo5 with advantage : 5 + Series score at 1

my tournament have Bo1, Bo2, Bo3, Bo5 with advantage, what is the best settings ?

what is the difference between num_maps and maptowin ?

**Comment by PhlexPlexico** [comment]
Yes, this is indeed how the BO2 series work, you just have to make sure "num_maps" has to be set to "2". `bo2_series` and `maps_to_win` are deprecated, so you can just use `num_maps` and set that to 2 instead of `maps_to_win`.

https://github.com/splewis/get5/blob/2a2063ec9bf3ff230be2b736df3a924ba0a58123/scripting/get5/matchconfig.sp#L343-L344

**Comment by Iwhite67** [comment]
Thanks you for this information, I made the change in the config


_________________________

Alexis Zaun
Technicien SAV Nord Est

FOM Industrie FRANCE

***@***.******@***.***>
(+33) 06 40 62 82 45
________________________________

**Comment by Iwhite67** [comment]
so, after test i have

Bo1 : num_map 1
Bo2 : num_map 2
Bo3 : num_map 3
Bo5 : num_map 5
Bo5 Advantage : maps_to_win 3 + Series score 1
