### ISSUE TITLE
https://github.com/splewis/get5/blob/849cf3c76f33869e0b6bdb21ea7fa9e1c9caea82/scripting/get5/matchconfig.sp#L150

### ISSUE THREAD

**Issue by Ankodo** [splewis/get5#748]
https://github.com/splewis/get5/blob/849cf3c76f33869e0b6bdb21ea7fa9e1c9caea82/scripting/get5/matchconfig.sp#L150

get5 is just using the normal sourcemod api to read files, so unfortunately I don't think there's anything we can do to help here. You'd have to debug your file system issues yourself most likely.

_Originally posted by @splewis in https://github.com/splewis/get5/issues/411#issuecomment-508959746_

**Comment by Ankodo** [comment]
[get5.smx] Failed to load match config: Match kv file doesn't exist: "matchTEST.cfg"
Failed to load match config.

[Terminal ](https://disk.yandex.ru/d/qXtvqCFQwGEOuA)

**Comment by PhlexPlexico** [comment]
Where exactly is `matchTEST.cfg` placed on the game server? I believe all the file checks have the source folder set to `csgo` (where the `cfg` folder, `addons` folder, etc. reside), so make sure you have the CFG file in either the "root" folder (so to speak) or you type out the path to the config (say if it's under `config/matchTEST.cfg` it would be `get5_loadmatch config/matchTEST.cfg`).

**Comment by Ankodo** [comment]
Path to` matchTEST.cfg` - `/home/steam/steamcmd/csgo/csgo/cfg`
The problem is that even if you enter the wrong file, it produces the same thing.

In addition, a new problem appeared - on the physical server. When I run through `!get5` match. I'm getting kicked from the server. With a message that `I am not a player in the current match.`

**Comment by PhlexPlexico** [comment]
So to load you would call `get5_loadmatch cfg/matchTEST.cfg` to load. 

As for the being kicked, please make sure you read what all the convars do in the get5 config. You probably have `get5_check_auths` set to `1` instead of `0`.

And please make sure `matchTEST.cfg` matches the key/value pairs to that of the example match configs seen [here](https://github.com/splewis/get5/blob/master/configs/get5/example_match.cfg)

**Comment by PhlexPlexico** [comment]
What exactly do you mean "host a created match with current players"? How are you setting that up? Through the config? If so, it's because the config has the Steam IDs identified.

If you're setting it up through the `!get5` command, and starting a scrim, you must follow these instructions [here](https://github.com/splewis/get5/wiki/Using-get5-for-scrims).

If you want a bunch of debug logs to output to console, you can turn on `get5_debug 32` and it will output more debug info on the console, and the console usually saves to log files under the `logs` directory.

**Comment by PhlexPlexico** [comment]
If you would like more assistance with configuring get5, I would recommend you join the [discord](https://discord.gg/zmqEa4keCk) server! Going to close this as this isn't a bug, but more on the configuration/setup side and there has been no response for two months.
