### ISSUE TITLE
Feature Request: Send HTTP REST API request on end of match instead of mysql

### ISSUE THREAD

**Issue by potato20** [splewis/get5#77]
The idea is that at the end of a match, instead of writing stats to a mysql database, it should make an http POST request to an endpoint that the user can specify, where it sends all the stats in the body as JSON.

Ideally the server should also shutdown after the game ends (does it do this already?)

This shouldn't be too hard as steamworks is already a requirement, so sending a network request shouldn't be complicated (I just don't have a lot of experience in sourcemod scripting).

Thanks @splewis !

**Comment by Technoblazed** [comment]
A) These stats are correctly done in the way you mentioned, but to the get5-web api, a line of code changed and you'll have what you want.

B) By default is kicks all players from the server, but you could easily have the server run the quit command. The issue with that being that you would have to manually/automatically restart the server after which, otherwise what is the point of the shutdown.

**Comment by splewis** [comment]
- SteamWorks isn't a hard requirement for get5

- Sending stats via HTTP requests, like was said, is exactly what https://github.com/splewis/get5/blob/master/scripting/get5_apistats.sp is for, but it's only written for [my web interface](https://github.com/splewis/get5-web) in mind. If you want a different format you would just write your own plugin similar to get5_apistats.

- I don't want to mess with server shutdown in get5. How servers are shut down/stopped depends on how someone's servers are setup. Specific users can [extend get5](https://github.com/splewis/get5/blob/master/scripting/include/get5.inc).

**Comment by splewis** [comment]
I don't think there's anything to do here in get5, so I'm closing this.
