### ISSUE TITLE
Backup should store draw info

### ISSUE THREAD

**Issue by nickdnk** [splewis/get5#817]
I was working on the [backup path thing](https://github.com/splewis/get5/pull/793), when I came across this. It would appear that game series scores are saved to backups and also restored, but that this does not include draws.

Written to backup here:
https://github.com/splewis/get5/blob/b8d6aff3a3796ac594ad5288d9265aea102b4f5d/scripting/get5/backups.sp#L164-L165

Read from backup here:
https://github.com/splewis/get5/blob/b8d6aff3a3796ac594ad5288d9265aea102b4f5d/scripting/get5/backups.sp#L246-L247

All three reset to 0 here, when loading a match config during restore:

https://github.com/splewis/get5/blob/b8d6aff3a3796ac594ad5288d9265aea102b4f5d/scripting/get5/matchconfig.sp#L22-L23

And used here to calculate `Get5_GetMapNumber`:

https://github.com/splewis/get5/blob/b8d6aff3a3796ac594ad5288d9265aea102b4f5d/scripting/get5/natives.sp#L203-L206

... so when a game is restored and a map was a draw, it's going to be wrong. Unless I'm missing something here.

**Comment by PhlexPlexico** [comment]
When loading a match, yes, but these values are brought in through `LoadTeamData`, as seen here.

https://github.com/splewis/get5/blob/b8d6aff3a3796ac594ad5288d9265aea102b4f5d/scripting/get5/matchconfig.sp#L655

Even though they get zeroed out, they are reinstantiated.

How exactly is it calculated on match draw when the map ends? Would it be set to 1 and 1 for each team? I can see the restore will always get it in the LoadTeamData call that's called from `LoadMatch`.

**Comment by PhlexPlexico** [comment]
Also I think there are no draws in competitive play, there is always a result, no matter the amount of overtime played, right?

**Comment by nickdnk** [comment]
> Also I think there are no draws in competitive play, there is always a result, no matter the amount of overtime played, right?

You can disable overtime and just play 15-15.

I see the team info being set, yes, but draws are attributed as wins to `Get5Team_None`. I don't see how they are loaded with the code you linked?

**Comment by deLuXe83** [comment]
Hi,
I can confirm this bug!

Had it multiple times - matches drawed, but stats are not recorded correct.

See for example matches 53, 55 & 57; all bo2 matches!
But the stats could mixed up. It always happen, when first map ended as draw!

Match 53: 1st map draw, 2nd map team2 => wrong in stats; correct was: 10:10 in map1, 7:13 in map2
Match 55: 1st map team1, 2nd map draw => correct in stats
MAtch 57: 1st map draw, 2nd map team 1 => wrong in stats; correct was: 10:10 in map1, 12:8 in map2

**get5_stats_maps:**

```

(52, 0, '2021-12-03 21:25:47', '2021-12-03 21:58:57', 'team2', 'workshop/2105680462/de_firenze', 5, 15),
(52, 1, '2021-12-03 22:02:14', '2021-12-03 22:31:44', 'team2', 'workshop/1483111472/de_scarab', 9, 11),
(53, 0, '2021-12-03 21:26:01', '2021-12-03 21:49:47', 'none', 'workshop/2105680462/de_firenze', 7, 13),
(53, 1, '2021-12-03 21:52:36', '2021-12-03 22:17:15', 'team2', 'workshop/1483111472/de_scarab', 0, 0),
(54, 0, '2021-12-03 22:38:18', '2021-12-03 23:25:58', 'team2', 'de_cbble', 9, 11),
(54, 1, '2021-12-03 23:30:10', '2021-12-04 00:01:38', 'team2', 'de_train', 8, 12),
(55, 0, '2021-12-03 22:38:09', '2021-12-03 23:10:37', 'team1', 'de_canals', 15, 5),
(55, 1, '2021-12-03 23:15:45', '2021-12-03 23:48:00', 'none', 'de_cbble', 10, 10),
(56, 0, '2021-12-04 00:09:06', '2021-12-04 00:38:47', 'team1', 'workshop/1483111472/de_scarab', 12, 8),
(56, 1, '2021-12-04 00:41:03', '2021-12-04 01:08:55', 'team2', 'de_dust2', 8, 12),
(57, 0, '2021-12-04 00:09:01', '2021-12-04 00:39:55', 'none', 'de_basalt', 12, 8),
(57, 1, '2021-12-04 00:41:44', '2021-12-04 01:10:51', 'team1', 'workshop/2105680462/de_firenze', 0, 0),

```
**get5_stats_matches:**

```
(52, '2021-12-03 21:16:28', '2021-12-03 22:32:09', 'team2', 'bo2', 'TEAM_C', 0, 'TEAM_D', 2, 2),
(53, '2021-12-03 21:18:56', '2021-12-03 22:17:40', 'team2', 'bo2', 'TEAM_A', 0, 'TEAM_B', 1, 9),
(54, '2021-12-03 22:32:20', '2021-12-04 00:02:02', 'team2', 'bo2', 'TEAM_A', 0, 'TEAM_C', 2, 9),
(55, '2021-12-03 22:32:42', '2021-12-03 23:48:25', 'team1', 'bo2', 'TEAM_B', 1, 'TEAM_D', 0, 2),
(56, '2021-12-04 00:02:12', '2021-12-04 01:09:20', 'none', 'bo2', 'TEAM_B', 1, 'TEAM_C', 1, 2),
(57, '2021-12-04 00:02:24', '2021-12-04 01:11:16', 'team1', 'bo2', 'TEAM_A', 1, 'TEAM_D', 0, 9),

```
And the bug continues to the player stats as well, because as you can see, in the SQL tables, all the lines with the inccorect stats are missing!

`(52, 0, 76561197960300580, 'team1', 20, 'schakal.exe', 15, 17, 0, 0, 0, 0, 7, 1461, 68, 4, 0, 3, 0, 0, 0, 0, 0, 0, 4, 0, 0, 0, 3, 4, 2, 2, 2, 12, 37, 0),
(52, 0, 76561197961650532, 'team2', 20, 'H∑︎NGST.exe', 18, 11, 3, 0, 0, 0, 3, 1806, 0, 5, 0, 2, 1, 1, 0, 0, 0, 0, 5, 0, 0, 0, 1, 2, 1, 2, 1, 15, 46, 4),
(52, 0, 76561197968336318, 'team1', 20, 'mAnni', 10, 18, 2, 0, 0, 0, 2, 1280, 43, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 2, 2, 2, 1, 12, 26, 0),
(52, 0, 76561197996680830, 'team2', 20, 'General Problem', 13, 11, 4, 0, 0, 0, 5, 1528, 0, 0, 0, 1, 2, 1, 1, 0, 0, 0, 2, 0, 1, 0, 2, 1, 4, 1, 0, 14, 38, 5),
(52, 0, 76561198069687775, 'team1', 20, 'Captain komMando.exe', 9, 17, 1, 0, 0, 0, 3, 1215, 11, 4, 0, 0, 1, 0, 0, 0, 0, 0, 2, 0, 0, 0, 1, 3, 1, 3, 0, 7, 21, 4),
(52, 0, 76561198069799791, 'team2', 20, 'LaGente', 17, 9, 4, 0, 0, 0, 5, 1915, 98, 0, 0, 2, 0, 0, 0, 0, 0, 0, 5, 0, 0, 0, 4, 4, 4, 2, 1, 16, 44, 3),
(52, 0, 76561198073369697, 'team2', 20, 'Marv', 18, 15, 1, 0, 1, 0, 7, 1614, 9, 2, 2, 1, 0, 0, 0, 0, 0, 0, 5, 0, 0, 0, 3, 2, 1, 3, 2, 14, 38, 3),
(52, 0, 76561198075776570, 'team1', 20, 'balRoger', 11, 15, 1, 0, 0, 1, 2, 1353, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 3, 1, 4, 3, 1, 11, 26, 1),
(52, 1, 76561197960300580, 'team1', 20, 'schakal.exe', 10, 15, 1, 0, 0, 0, 3, 1206, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 3, 2, 3, 1, 0, 12, 21, 1),
(52, 1, 76561197961650532, 'team2', 20, 'H∑︎NGST.exe', 12, 13, 3, 0, 0, 0, 3, 1336, 0, 2, 0, 1, 0, 1, 0, 0, 0, 0, 5, 0, 0, 0, 3, 1, 1, 4, 1, 12, 30, 3),
(52, 1, 76561197968336318, 'team1', 20, 'mAnni', 13, 12, 0, 0, 0, 0, 5, 1518, 5, 1, 0, 3, 0, 0, 0, 0, 0, 0, 3, 0, 0, 0, 1, 3, 3, 5, 1, 11, 35, 2),
(52, 1, 76561197996680830, 'team2', 20, 'General Problem', 8, 14, 0, 0, 0, 0, 2, 708, 0, 0, 0, 6, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 2, 1, 2, 2, 2, 10, 29, 0),
(52, 1, 76561198069687775, 'team1', 20, 'Captain komMando.exe', 9, 14, 4, 0, 0, 0, 3, 1392, 356, 1, 1, 3, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 3, 1, 12, 32, 1),
(52, 1, 76561198069799791, 'team2', 20, 'LaGente', 23, 11, 1, 0, 0, 0, 7, 2112, 45, 0, 0, 1, 0, 1, 0, 1, 0, 0, 7, 0, 1, 0, 1, 4, 2, 1, 0, 15, 53, 6),
(52, 1, 76561198073369697, 'team2', 20, 'Marv', 13, 15, 4, 0, 0, 0, 7, 1743, 44, 1, 0, 0, 0, 0, 0, 0, 0, 0, 4, 0, 0, 0, 3, 3, 4, 3, 2, 12, 32, 2),
(52, 1, 76561198075776570, 'team1', 20, 'balRoger', 20, 15, 1, 0, 0, 0, 5, 1848, 132, 0, 0, 2, 0, 0, 1, 0, 0, 0, 6, 1, 0, 0, 5, 3, 2, 0, 1, 12, 47, 5),
(53, 0, 76561197963572337, 'team2', 20, 'sChmiero', 11, 12, 3, 0, 0, 0, 2, 1521, 58, 0, 0, 1, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 3, 3, 1, 1, 0, 13, 29, 2),
(53, 0, 76561197980701482, 'team1', 20, 'Kilr0y.exe', 12, 13, 5, 0, 0, 0, 4, 1426, 131, 1, 2, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 2, 2, 2, 2, 1, 15, 34, 1),
(53, 0, 76561198013444801, 'team2', 20, 'eXecutoR^', 7, 15, 5, 0, 0, 0, 2, 1147, 193, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 2, 0, 9, 21, 1),
(53, 0, 76561198018584388, 'team2', 20, 'FoxJoschi', 25, 13, 3, 0, 0, 0, 5, 2167, 15, 5, 0, 2, 0, 1, 1, 0, 0, 0, 7, 2, 0, 0, 3, 5, 4, 0, 1, 14, 59, 5),
(53, 0, 76561198045030468, 'team2', 20, 'EddyEagle.exe', 9, 17, 3, 0, 1, 0, 4, 1156, 127, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 1, 5, 6, 0, 11, 19, 2),
(53, 0, 76561198250441212, 'team1', 20, 'Timmey', 19, 11, 3, 0, 0, 0, 8, 1954, 0, 1, 0, 1, 1, 2, 0, 0, 0, 0, 6, 1, 0, 0, 2, 2, 3, 2, 0, 13, 46, 5),
(53, 0, 76561198847241077, 'team1', 20, 'ludat69', 13, 14, 2, 0, 0, 0, 5, 1518, 14, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 1, 0, 0, 3, 3, 3, 1, 1, 12, 28, 2),
(53, 0, 76561199045654437, 'team1', 20, 'Toni.exe', 11, 14, 0, 0, 0, 0, 3, 1221, 58, 2, 3, 1, 0, 0, 0, 0, 0, 0, 3, 0, 0, 0, 2, 3, 1, 2, 0, 11, 25, 2),
(54, 0, 76561197960300580, 'team2', 20, 'schakal.exe', 9, 12, 3, 1, 0, 0, 1, 1097, 0, 8, 2, 1, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 2, 1, 1, 1, 13, 27, 2),
(54, 0, 76561197968336318, 'team2', 20, 'mAnni', 19, 12, 3, 0, 0, 0, 8, 2143, 75, 5, 0, 3, 0, 0, 0, 0, 0, 0, 4, 0, 1, 0, 5, 1, 1, 4, 1, 14, 49, 5),
(54, 0, 76561197980701482, 'team1', 20, 'Kilr0y.exe', 11, 14, 0, 0, 0, 0, 5, 1194, 2, 0, 3, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 2, 2, 1, 0, 10, 27, 1),
(54, 0, 76561198069687775, 'team2', 20, 'Captain komMando.exe', 15, 13, 3, 0, 0, 0, 4, 1519, 8, 4, 0, 2, 0, 0, 0, 0, 0, 0, 4, 1, 0, 0, 1, 4, 4, 2, 0, 14, 38, 2),
(54, 0, 76561198075776570, 'team2', 20, 'balRoger', 17, 9, 1, 0, 0, 0, 8, 1626, 26, 0, 1, 1, 0, 0, 0, 0, 0, 0, 5, 0, 0, 0, 3, 3, 3, 1, 1, 16, 39, 2),
(54, 0, 76561198250441212, 'team1', 20, 'Timmey', 23, 13, 0, 0, 0, 1, 11, 2325, 68, 3, 0, 3, 0, 0, 2, 1, 0, 0, 3, 2, 1, 0, 3, 4, 1, 3, 0, 14, 58, 6),
(54, 0, 76561198847241077, 'team1', 20, 'ludat69', 4, 16, 1, 0, 0, 0, 3, 728, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 4, 0, 7, 14, 1),
(54, 0, 76561199045654437, 'team1', 20, 'Toni.exe', 8, 17, 1, 0, 0, 0, 1, 955, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 4, 3, 5, 1, 0, 10, 17, 1),
(54, 1, 76561197960300580, 'team2', 20, 'schakal.exe', 16, 13, 4, 0, 0, 0, 4, 1688, 19, 2, 0, 3, 0, 0, 0, 0, 0, 0, 5, 1, 0, 0, 3, 2, 0, 4, 1, 13, 47, 3),
(54, 1, 76561197968336318, 'team2', 20, 'mAnni', 17, 15, 6, 0, 0, 0, 4, 1938, 0, 2, 0, 1, 0, 0, 0, 0, 0, 0, 3, 1, 0, 0, 5, 3, 5, 4, 0, 17, 45, 2),
(54, 1, 76561197980701482, 'team1', 20, 'Kilr0y.exe', 10, 14, 4, 0, 0, 1, 3, 1292, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 1, 2, 4, 3, 0, 11, 28, 1),
(54, 1, 76561198069687775, 'team2', 20, 'Captain komMando.exe', 16, 11, 1, 0, 0, 0, 4, 1655, 32, 1, 0, 2, 0, 0, 1, 0, 0, 0, 2, 0, 1, 0, 1, 3, 2, 1, 0, 15, 39, 2),
(54, 1, 76561198075776570, 'team2', 20, 'balRoger', 10, 13, 3, 0, 0, 0, 2, 1218, 47, 1, 0, 2, 1, 0, 0, 0, 0, 0, 3, 0, 0, 0, 1, 2, 2, 0, 0, 10, 36, 5),
(54, 1, 76561198250441212, 'team1', 20, 'Timmey', 25, 15, 3, 0, 0, 0, 8, 2427, 85, 3, 1, 1, 1, 0, 0, 0, 0, 0, 5, 3, 0, 0, 4, 6, 2, 3, 0, 15, 60, 5),
(54, 1, 76561198847241077, 'team1', 20, 'ludat69', 5, 15, 2, 0, 0, 0, 1, 959, 0, 0, 0, 3, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 7, 21, 1),
(54, 1, 76561199045654437, 'team1', 20, 'Toni.exe', 11, 15, 3, 0, 0, 0, 2, 1273, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 3, 1, 3, 3, 0, 11, 26, 1),
(55, 0, 76561197961650532, 'team2', 20, 'H∑︎NGST.exe', 8, 19, 4, 0, 0, 0, 4, 1019, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 2, 2, 4, 4, 0, 10, 21, 1),
(55, 0, 76561197963572337, 'team1', 20, 'sChmiero', 23, 8, 2, 0, 0, 0, 10, 2167, 37, 0, 0, 3, 1, 1, 2, 0, 0, 0, 3, 2, 1, 0, 2, 3, 1, 2, 1, 17, 60, 8),
(55, 0, 76561197996680830, 'team2', 20, 'General Problem', 7, 18, 7, 0, 0, 0, 2, 1395, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 3, 4, 1, 0, 12, 25, 1),
(55, 0, 76561198013444801, 'team1', 20, 'eXecutoR^', 15, 13, 2, 0, 0, 0, 3, 1645, 21, 3, 0, 1, 0, 0, 0, 0, 0, 0, 3, 0, 0, 0, 1, 3, 3, 1, 0, 18, 34, 0),
(55, 0, 76561198018584388, 'team1', 20, 'FoxJoschi', 24, 13, 3, 0, 0, 0, 8, 2654, 3, 4, 1, 2, 0, 0, 0, 1, 0, 0, 7, 1, 0, 0, 4, 4, 0, 4, 0, 17, 55, 7),
(55, 0, 76561198045030468, 'team1', 20, 'EddyEagle.exe', 8, 15, 0, 0, 0, 0, 5, 847, 34, 0, 0, 2, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 3, 0, 4, 2, 1, 9, 22, 1),
(55, 0, 76561198069799791, 'team2', 20, 'LaGente', 25, 17, 2, 0, 0, 0, 8, 2058, 10, 0, 0, 1, 0, 0, 1, 0, 0, 0, 6, 2, 0, 0, 3, 2, 0, 1, 0, 16, 55, 2),
(55, 0, 76561198073369697, 'team2', 20, 'Marv', 9, 16, 3, 0, 0, 0, 2, 1208, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 4, 1, 2, 4, 1, 13, 24, 1),
(55, 1, 76561197961650532, 'team2', 20, 'H∑︎NGST.exe', 14, 15, 7, 0, 0, 0, 6, 1862, 6, 3, 0, 0, 0, 0, 0, 0, 0, 0, 3, 0, 0, 0, 4, 4, 5, 1, 1, 13, 36, 0),
(55, 1, 76561197963572337, 'team1', 20, 'sChmiero', 17, 12, 4, 0, 0, 0, 7, 1869, 289, 0, 0, 3, 1, 1, 1, 0, 0, 0, 4, 1, 0, 0, 3, 4, 1, 1, 2, 14, 49, 4),
(55, 1, 76561197996680830, 'team2', 20, 'General Problem', 14, 11, 2, 0, 0, 0, 4, 1129, 48, 2, 0, 3, 2, 1, 1, 0, 0, 0, 4, 1, 0, 0, 0, 0, 0, 2, 0, 11, 40, 5),
(55, 1, 76561198013444801, 'team1', 20, 'eXecutoR^', 4, 15, 0, 0, 0, 0, 0, 496, 109, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 4, 3, 0, 7, 11, 0),
(55, 1, 76561198018584388, 'team1', 20, 'FoxJoschi', 21, 16, 5, 0, 0, 0, 5, 2288, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3, 2, 0, 0, 5, 2, 2, 5, 2, 16, 47, 4),
(55, 1, 76561198045030468, 'team1', 20, 'EddyEagle.exe', 12, 14, 3, 0, 0, 0, 4, 1282, 96, 0, 0, 2, 1, 1, 0, 0, 0, 0, 2, 0, 0, 0, 0, 3, 3, 0, 0, 14, 33, 2),
(55, 1, 76561198069799791, 'team2', 20, 'LaGente', 13, 15, 1, 0, 0, 0, 7, 1269, 22, 2, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 2, 1, 3, 3, 1, 10, 33, 2),
(55, 1, 76561198073369697, 'team2', 20, 'Marv', 16, 13, 4, 0, 0, 0, 10, 1707, 0, 2, 0, 1, 0, 0, 0, 0, 0, 0, 5, 0, 0, 0, 3, 5, 1, 3, 0, 16, 38, 3),
(56, 0, 76561197960300580, 'team2', 20, 'schakal.exe', 16, 15, 5, 0, 0, 0, 6, 1731, 0, 3, 0, 1, 0, 1, 0, 0, 0, 0, 3, 1, 0, 0, 0, 1, 2, 2, 1, 15, 40, 3),
(56, 0, 76561197963572337, 'team1', 20, 'sChmiero', 17, 13, 4, 0, 0, 0, 9, 1856, 268, 0, 1, 0, 0, 0, 0, 0, 0, 0, 4, 0, 0, 0, 2, 3, 2, 1, 4, 14, 41, 1),
(56, 0, 76561197968336318, 'team2', 20, 'mAnni', 13, 16, 6, 0, 0, 0, 2, 1826, 0, 3, 3, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 2, 4, 4, 2, 0, 15, 32, 1),
(56, 0, 76561198013444801, 'team1', 20, 'eXecutoR^', 11, 16, 3, 0, 0, 1, 4, 997, 105, 7, 2, 1, 0, 2, 0, 0, 0, 0, 1, 1, 0, 0, 2, 1, 2, 1, 1, 13, 29, 1),
(56, 0, 76561198018584388, 'team1', 20, 'FoxJoschi', 27, 13, 2, 0, 0, 0, 12, 2600, 0, 1, 0, 2, 1, 1, 2, 0, 0, 0, 7, 3, 0, 0, 4, 3, 4, 3, 3, 15, 68, 8),
(56, 0, 76561198045030468, 'team1', 20, 'EddyEagle.exe', 3, 17, 4, 0, 0, 0, 1, 814, 25, 0, 0, 3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 2, 1, 5, 0, 9, 18, 2),
(56, 0, 76561198069687775, 'team2', 20, 'Captain komMando.exe', 11, 13, 3, 0, 0, 0, 2, 1177, 98, 0, 1, 2, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 3, 2, 1, 0, 16, 30, 1),
(56, 0, 76561198075776570, 'team2', 20, 'balRoger', 18, 14, 0, 0, 0, 0, 7, 1563, 50, 2, 0, 1, 0, 1, 0, 0, 0, 0, 5, 1, 0, 0, 8, 1, 1, 4, 4, 13, 40, 3),
(56, 1, 76561197960300580, 'team2', 20, 'schakal.exe', 7, 13, 1, 0, 0, 0, 1, 778, 0, 2, 0, 1, 0, 0, 1, 0, 0, 0, 2, 0, 0, 0, 0, 0, 2, 2, 0, 8, 18, 1),
(56, 1, 76561197963572337, 'team1', 20, 'sChmiero', 20, 14, 5, 2, 0, 0, 10, 2282, 182, 15, 1, 0, 0, 0, 0, 0, 0, 0, 1, 3, 1, 0, 3, 5, 2, 1, 1, 14, 45, 3),
(56, 1, 76561197968336318, 'team2', 20, 'mAnni', 21, 12, 5, 0, 0, 0, 4, 2256, 74, 0, 2, 1, 0, 0, 0, 0, 0, 0, 5, 1, 0, 0, 4, 3, 5, 2, 1, 17, 50, 4),
(56, 1, 76561198013444801, 'team1', 20, 'eXecutoR^', 8, 15, 2, 0, 0, 0, 1, 1007, 146, 0, 1, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 3, 1, 1, 4, 0, 13, 18, 1),
(56, 1, 76561198018584388, 'team1', 20, 'FoxJoschi', 16, 15, 3, 0, 0, 1, 6, 2049, 14, 1, 0, 0, 1, 1, 0, 0, 0, 0, 2, 0, 1, 0, 2, 2, 4, 2, 2, 12, 37, 3),
(56, 1, 76561198045030468, 'team1', 20, 'EddyEagle.exe', 8, 15, 1, 0, 0, 0, 3, 706, 45, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 2, 2, 2, 0, 9, 21, 1),
(56, 1, 76561198069687775, 'team2', 20, 'Captain komMando.exe', 11, 12, 1, 1, 0, 0, 3, 1248, 42, 6, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 12, 27, 2),
(56, 1, 76561198075776570, 'team2', 20, 'balRoger', 20, 15, 3, 0, 0, 0, 3, 2017, 89, 4, 4, 2, 0, 0, 0, 0, 0, 0, 3, 2, 0, 0, 5, 5, 3, 4, 0, 14, 49, 5),
(57, 0, 76561197961650532, 'team2', 20, 'H∑︎NGST.exe', 12, 13, 1, 0, 0, 0, 6, 925, 51, 0, 0, 2, 2, 1, 0, 0, 0, 0, 0, 1, 0, 0, 3, 2, 5, 1, 1, 13, 33, 2),
(57, 0, 76561197980701482, 'team1', 20, 'Kilr0y.exe', 8, 15, 3, 0, 0, 0, 3, 1353, 98, 0, 0, 1, 1, 0, 0, 0, 0, 0, 2, 0, 0, 0, 1, 3, 2, 2, 1, 11, 26, 3),
(57, 0, 76561197996680830, 'team2', 20, 'General Problem', 11, 13, 4, 0, 0, 0, 2, 1415, 4, 3, 0, 2, 0, 1, 0, 0, 0, 0, 3, 0, 0, 0, 1, 3, 2, 4, 1, 15, 31, 2),
(57, 0, 76561198069799791, 'team2', 20, 'LaGente', 20, 14, 5, 0, 0, 0, 6, 2153, 27, 0, 0, 0, 0, 0, 1, 0, 0, 0, 4, 2, 0, 0, 5, 4, 2, 3, 1, 17, 45, 3),
(57, 0, 76561198073369697, 'team2', 20, 'Marv', 18, 15, 3, 0, 0, 0, 6, 1756, 56, 1, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 1, 0, 1, 1, 0, 1, 1, 13, 40, 3),
(57, 0, 76561198250441212, 'team1', 20, 'Timmey', 18, 14, 4, 1, 0, 0, 6, 1761, 0, 4, 2, 1, 0, 1, 1, 0, 0, 0, 4, 1, 0, 0, 2, 2, 3, 1, 2, 14, 44, 2),
(57, 0, 76561198847241077, 'team1', 20, 'ludat69', 15, 17, 0, 0, 0, 0, 4, 1462, 73, 0, 0, 2, 1, 0, 0, 0, 0, 0, 1, 2, 0, 0, 3, 1, 3, 5, 1, 13, 42, 3),
(57, 0, 76561199045654437, 'team1', 20, 'Toni.exe', 14, 17, 3, 0, 0, 0, 3, 1623, 50, 0, 4, 1, 0, 2, 0, 0, 0, 0, 3, 1, 0, 0, 3, 3, 2, 2, 1, 13, 34, 2),`

And last thing to add:
in the get5_matchstats_xx.cfg files for each match the stats are correct :)


Looking very much forward for this fix!!!
Thank you for your great work!!!!

**Comment by nickdnk** [comment]
@deLuXe83 This is fixed in https://github.com/splewis/get5/pull/821. Can you try this version just to confirm that it works as you expect? You can download it here: https://github.com/splewis/get5/suites/7762332138/artifacts/326223535

**Comment by deLuXe83** [comment]
thx!

yes I'll give it a try.
But might take a few days, not much action in our group right now... :/

**Comment by nickdnk** [comment]
Alright. Just playing with this version, even a single game, would be fine, just to make sure I didn't break anything. You don't need to play a draw to give feedback.

**Comment by nickdnk** [comment]
Update: Use this build instead: https://github.com/splewis/get5/suites/7780053824/artifacts/327471333 - fixed some problems related to GOTV and match_restart_delay
