### ISSUE TITLE
Loading match from URL is broken

### ISSUE THREAD

**Issue by shavitush** [splewis/get5#86]
### Expected behavior

The match should load properly, without any "team1 missing" error.

### Actual behavior

    L 11/14/2016 - 15:57:56: Info (map "de_dust2") (file "errors_20161114.log")
    L 11/14/2016 - 15:57:56: [get5.smx] Failed to load match config: Missing "team1" section in match json
    L 11/14/2016 - 15:57:56: [get5.smx] Failed to load match config: invalid match json

### Steps to reproduce
Run the following command:

    get5_loadmatch_url "https://raw.githubusercontent.com/splewis/get5/master/configs/get5/example_match.json"

- Plugin version: 0.4.1-dev+239
- Sourcemod version: 1.8.0.5950

I use SteamWorks instead of System2 for loading from URLs - if it matters.

Edit: Changed to System2 and I don't get the error anymore! System2 requires me to not specify the http/https protocols though.

**Comment by Technoblazed** [comment]
I couldn't get it to work at all without System2, just kept crashing :D

**Comment by splewis** [comment]
For what it's worth, I'd more comfortable having SteamWorks as a dependency than system2, so it not working is a very strange issue. I'll try to look into this. One step in debugging is to run the command (with steamworks enabled, and system2), and see what the file downloaded is (it's saved to remote.json).

**Comment by splewis** [comment]
Since both steamworks and system2 have differences between whether to include http:// in the url, I changed it to handle with/without it: af57b46d0275ed48287d2bd08d5b4e9540c14d92

Things seem to work more reliably now with both steamworks and system2 with/without http://.

I still haven't tested against https:// urls. AFAIK, the steam client doesn't support SSL though system2 seems to now. I might be wrong.

**Comment by splewis** [comment]
I believe this is fixed. Feel free to reopen if you have another issue with either steamworks or system2.
