### ISSUE TITLE
[Feature Request]: Post match stats to API once game is done.

### ISSUE THREAD

**Issue by LukasW1337** [splewis/get5#990]
### Prereleases & Documentation

- [X] I have looked in [the documentation](https://splewis.github.io/get5) and I don't see the feature anywhere.
- [X] I have looked for [pre-releases](https://github.com/splewis/get5/releases) and the feature has not been added.

### Get5 Version

0.13.0

### The Feature

Feature would work the same as demo upload after map ends.
Define endpoint, authorization etc. 

Once map is done, it uploads or post the `get5_matchstats_{MATCHID}.cfg`

**Comment by nickdnk** [comment]
It seems like SteamWorks will only allow me to send 4096 bytes, unless I choose to upload a file from disk. I have no idea where this limitation is coming from or why it is there, but it makes at fairly difficult to send the full match stats on round end, which was my original plan.

There is still the option of writing the JSON stats to a file and then uploading that file on map end instead, because we *can* do that, for some reason. Because this requires disk I/O, I may not want to do that on every round end. I have to figure out if there is a performance issue in doing that first.

**Comment by LowArte** [comment]
https://forums.alliedmods.net/showthread.php?t=298174
Maybe be helpful
